### ISSUE TITLE
sourcemaps not working, debugger breakpoints always on 1st line

### ISSUE THREAD

**Issue by max-l** [VISI-ONE/create-react-native-web-app#26] opened 2018-12-16 19:50 UTC
I just created a project with version 0.1.9, added an onClick function on the demo page, 
and the debugger always break on first line.  

Note that I am seeing the correct untransformed source file in the debugger 
console when the breadpoint is hit (debugger key word).

The debugger will not let me set breakpoints on other lines,
it is as if it is working with the minimized file while displaying the proper source file.

The problem is on both Chrome and Firefox

the devtool variable in the webpack config seems correct ('cheap-module-source-map')
I tried changing it without success.

**Comment by max-l** [comment] 2018-12-16 20:35
The problem got solved by removing the 'babel-preset-expo' preset
in babel.config.js


```
module.exports = function(api) {

  api.cache(true);
  return {
  "plugins": [
      ["module-resolver", {
        "alias": {
          "^react-native$": "react-native-web"
        }
      }]
    ],
    presets: [["react-app"]], //, ['babel-preset-expo']
  };
};
```

**Comment by orYoffe** [comment] 2018-12-20 09:43
duplicate of #18 will fix soon

**Closed by orYoffe** 2018-12-20 09:43 UTC

**Comment by pilot4u** [comment] 2019-06-12 04:54
I still experience this issue with version 0.11.4

.babelrc:
`{
  "presets": [
    "react-native",
    [
      "@babel/preset-env",
      {
        "modules": "commonjs",
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-react"
  ],
  "retainLines": true,
  "plugins": [
    "react-native-web",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "no-side-effect-class-properties",
    "@babel/plugin-transform-runtime",
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "inline-import-graphql-ast",
    "babel-plugin-react-persist",
    [
      "@babel/plugin-transform-arrow-functions",
      {
        "spec": false
      }
    ],
    "import-graphql"
  ]
}`

webpack.config.js:
`const path = require("path");
const webpack = require("webpack");
const HtmlWebPackPlugin = require("html-webpack-plugin");

const appDirectory = path.resolve(__dirname, "../");

// This is needed for webpack to compile JavaScript.
// Many OSS React Native packages are not compiled to ES5 before being
// published. If you depend on uncompiled packages they may cause webpack build
// errors. To fix this webpack can be configured to compile to the necessary
// `node_module`.
const babelLoaderConfiguration = {
  test: /\.js$/,
  // Add every directory that needs to be compiled by Babel during the build.
  include: [
    path.resolve(appDirectory, "web/index.web.js"),
    path.resolve(appDirectory, "src"),
    path.resolve(appDirectory, "node_modules/react-native-uncompiled"),
    path.resolve(appDirectory, "node_modules")
  ],
  use: {
    loader: "babel-loader",
    options: {
      cacheDirectory: true,
      // The 'react-native' preset is recommended to match React Native's packager
      presets: ["react-native", ["@babel/preset-env"], "@babel/preset-react", "@babel/preset-flow"],
      // Re-write paths to import only the modules needed by the app
      plugins: [
        "react-native-web",
        ["@babel/plugin-proposal-class-properties", { loose: true }],
        "@babel/plugin-proposal-object-rest-spread",
        "import-graphql"
      ]
    }
  }
};

// This is needed for webpack to import static images in JavaScript files.
const imageLoaderConfiguration = {
  test: /\.(gif|jpe?g|png|svg)$/,
  use: {
    loader: "url-loader",
    options: {
      name: "[name].[ext]"
    }
  }
};

module.exports = {
  entry: [
    // load any web API polyfills
    // path.resolve(appDirectory, 'polyfills-web.js'),
    // your web-specific entry file
    path.resolve(appDirectory, "index.web.js")
  ],

  // configures where the build ends up
  output: {
    filename: "bundle.web.js",
    path: path.resolve(appDirectory, "web")
  },

  // ...the rest of your config
  devtool: "cheap-module-source-map",
  module: {
    rules: [babelLoaderConfiguration, imageLoaderConfiguration]
  },
  plugins: [
    // `process.env.NODE_ENV === 'production'` must be `true` for production
    // builds to eliminate development checks and reduce build size. You may
    // wish to include additional optimizations.
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV || "development"),
      __DEV__: process.env.NODE_ENV === "production" || true
    }),
    new HtmlWebPackPlugin({
      template: "./public/index.html",
      filename: "index.html",
      inject: "body"
    })
  ],
  resolve: {
    // This will only alias the exact import "react-native"
    alias: {
      "react-native$": "react-native-web"
    },
    // If you're working on a multi-platform React Native app, web-specific
    // module implementations should be written in files using the extension
    // `.web.js`.
    extensions: [".web.js", ".js"]
  }
};
`

**Comment by orYoffe** [comment] 2019-06-12 19:17
@pilot4u 
try to change the sourcemap on webpack like in this repo (actually from create-react-app) comment explains if you put `eval` it might fix your issue
check it out here 👇 
https://github.com/orYoffe/create-react-native-web-app/blob/master/template/config/webpack.config.dev.js#L81
